import { notFound } from "next/navigation";
import { getTripManifestData } from "@/lib/admin/trip-manifest";
import { getSiteBranding } from "@/lib/site-branding";
import { formatTime } from "@/lib/dashboard/format";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ tripId: string }> }) {
  const { tripId } = await params;
  const data = await getTripManifestData(tripId);
  if (!data) return { title: "Manifest not found" };
  return {
    title: `Passenger Manifest — ${data.vesselName} | ${data.departureDate}`,
    description: `Official passenger manifest for ${data.vesselName}, ${data.routeName}, ${data.departureDate}.`,
  };
}

function formatDate(d: string): string {
  if (!d || d === "—") return "—";
  try {
    return new Date(d + "Z").toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" });
  } catch {
    return d;
  }
}

function formatTimestamp(ts: string | null): string {
  if (!ts) return "—";
  try {
    return new Date(ts).toLocaleTimeString("en-PH", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: true,
      timeZone: "Asia/Manila",
    });
  } catch {
    return "—";
  }
}

const statusLabel: Record<string, string> = {
  confirmed: "Confirmed",
  checked_in: "Checked in",
  boarded: "Boarded",
  completed: "Completed",
};

export default async function PublicManifestPage({
  params,
}: {
  params: Promise<{ tripId: string }>;
}) {
  const { tripId } = await params;
  const data = await getTripManifestData(tripId);
  if (!data) notFound();

  const branding = await getSiteBranding();

  const boardedCount = data.passengers.filter((p) => p.status === "boarded" || p.status === "completed").length;
  const checkedInCount = data.passengers.filter((p) => p.status === "checked_in").length;
  const confirmedCount = data.passengers.filter((p) => p.status === "confirmed").length;

  return (
    <div className="min-h-screen bg-white text-black p-6 sm:p-8 max-w-5xl mx-auto">
      {/* Header */}
      <div className="border-b-2 border-black pb-4 mb-4">
        <p className="text-xs uppercase tracking-wider text-gray-600">Republic of the Philippines</p>
        <h1 className="text-xl sm:text-2xl font-bold mt-1">PASSENGER MANIFEST</h1>
        <p className="text-sm text-gray-700 mt-0.5">For Philippine Coast Guard — Pre-Departure Clearance</p>
        <p className="text-xs text-gray-500 mt-1">Generated by {branding.site_name} booking system · Live data</p>
      </div>

      {/* Trip info */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4 text-sm">
        <div><span className="font-semibold">Vessel:</span> {data.vesselName}</div>
        <div><span className="font-semibold">Route:</span> {data.routeName}</div>
        <div><span className="font-semibold">Origin:</span> {data.origin}</div>
        <div><span className="font-semibold">Destination:</span> {data.destination}</div>
        <div><span className="font-semibold">Date of departure:</span> {formatDate(data.departureDate)}</div>
        <div><span className="font-semibold">Time of departure:</span> {formatTime(data.departureTime)}</div>
        <div><span className="font-semibold">Total passengers:</span> {data.totalPassengers}</div>
        <div><span className="font-semibold">Vessel capacity:</span> {data.capacity}</div>
      </div>

      {/* Boarding summary */}
      <div className="mb-4 flex flex-wrap gap-4 rounded border border-gray-300 bg-gray-50 px-4 py-3 text-sm">
        <div>
          <span className="font-semibold">Confirmed (not yet checked in):</span> {confirmedCount}
        </div>
        <div>
          <span className="font-semibold">Checked in (at pier):</span> {checkedInCount}
        </div>
        <div>
          <span className="font-semibold">Actually boarded:</span>{" "}
          <span className="font-bold">{boardedCount}</span>
        </div>
      </div>

      {/* Passenger table */}
      <div className="overflow-x-auto">
        <table className="w-full border-collapse border border-gray-800 text-sm">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">No.</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Ticket #</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Booking ref.</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Passenger name</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Type</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Address</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Contact</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Source</th>
              <th className="border border-gray-800 px-2 py-1.5 text-left font-semibold">Status</th>
            </tr>
          </thead>
          <tbody>
            {data.passengers.length === 0 ? (
              <tr>
                <td colSpan={9} className="border border-gray-800 px-2 py-3 text-center text-gray-600">
                  No passengers on manifest
                </td>
              </tr>
            ) : (
              data.passengers.map((p) => (
                <tr key={`${p.ticketNumber}-${p.seq}`}>
                  <td className="border border-gray-800 px-2 py-1">{p.seq}</td>
                  <td className="border border-gray-800 px-2 py-1 font-mono font-semibold">{p.ticketNumber}</td>
                  <td className="border border-gray-800 px-2 py-1">{p.reference}</td>
                  <td className="border border-gray-800 px-2 py-1">{p.passengerName}</td>
                  <td className="border border-gray-800 px-2 py-1">{p.fareType}</td>
                  <td className="border border-gray-800 px-2 py-1">{p.address ?? "—"}</td>
                  <td className="border border-gray-800 px-2 py-1">{p.contact ?? "—"}</td>
                  <td className="border border-gray-800 px-2 py-1">{p.source}</td>
                  <td className="border border-gray-800 px-2 py-1 min-w-[120px]">
                    <div className="font-semibold text-xs">
                      {statusLabel[p.status] ?? p.status}
                    </div>
                    {p.checkedInAt && (
                      <div className="text-xs text-gray-600">
                        In: {formatTimestamp(p.checkedInAt)}
                      </div>
                    )}
                    {p.boardedAt && (
                      <div className="text-xs font-semibold text-black">
                        ✓ Boarded: {formatTimestamp(p.boardedAt)}
                      </div>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {data.walkInNoNames > 0 && (
        <p className="mt-4 text-sm text-gray-700">
          <span className="font-semibold">Walk-in (count only):</span> {data.walkInNoNames} passenger{data.walkInNoNames !== 1 ? "s" : ""} sold at the pier but not listed by name above.
          Total: {data.totalListed} listed + {data.walkInNoNames} = <strong>{data.totalPassengers} total passengers</strong>.
        </p>
      )}

      <p className="mt-2 text-xs text-gray-600">
        Source: Online = booked on website; Walk-in = sold at ticket booth.
      </p>
      <p className="mt-1 text-xs text-gray-600">
        Status: Confirmed = booked but not yet at pier; Checked in = arrived at pier; Boarded = confirmed on vessel. Times are Philippines Standard Time (PST).
      </p>
      <p className="mt-4 text-xs text-gray-400 text-center">
        This is a live public manifest link. Data updates in real time. — {branding.site_name}
      </p>
    </div>
  );
}
